services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: market
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U market -d marketplace"]
      interval: 5s
      timeout: 3s
      retries: 5

  migrate:
    image: migrate/migrate:v4.17.0
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations:ro
    command:
      - -path=/migrations
      - -database=postgres://market:secret@db:5432/marketplace?sslmode=disable
      - up
    restart: on-failure

  api:
    build: .
    image: golang-marketplace-api:dev
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      DB_DSN: postgres://market:secret@db:5432/marketplace?sslmode=disable
    ports:
      - "8080:8080"