name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      
      - name: Go vet
        run: go vet ./...
      - name: Run unit tests
        run: go test -v ./...
      
      - name: Docker build
        run: docker build -t ghcr.io/\${{ github.hariyaki }}/golang-marketplace-api:ci .

      - name: Login to GHCR
        if: github.event_name == 'push' && env.GHCR_PAT != ''
        env:
          GHCR_PAT: \$\{{ secrets.GHCR_PAT }}
        run: echo "\$GHCR_PAT" | docker login ghcr.io -u \$\{{ github.hariyaki }} --password-stdin

      - name: Push image
        if: github.event_name =='push' && env.GHCR_PAT != ''
        run: docker push ghcr.io/\${{ github.hariyaki }}/golang-marketplace-api:ci
        